### PR TITLE
Update dust.js

### PR DESCRIPTION
**Pull request by leon-strong**
quick PR to fix dust script to match correct value if it's not already fixed.

### CODE REVIEW

**Comment by billbertking1** [comment]
https://github.com/AllTheMods/All-the-mods-9-Sky/commit/1930bad02e4c393e8bc9192c3b11234f1e670eda

**Comment by leon-strong** [comment]
doesn't it need to be updated in both places?

**Comment by billbertking1** [comment]
What do you mean both places?

**Comment by leon-strong** [comment]
ah nevermind, i just realized i was being dippy and looking at the wrong branch 😆

**Pull request closed without merging**
