### PR TITLE
redundant ores/awakened draconium dust fix

### PR DESCRIPTION
**Pull request by MisterPandy**
See #408 and #385 

Bug = #385
Enhancement = #408 

awakened draconium dust is needed for some recipes but is currently unobtainable.

### CODE REVIEW

**Comment by TheBedrockMaster** [comment]
I think they use KubeJS for JEI stuff.

**Comment by Pandy420** [comment]
I tested it before requesting

**Comment by TheBedrockMaster** [comment]
Not saying it's wrong or anything.

**Review by oly2o6 — APPROVED** [review]

**Comment by oly2o6** [comment]
Reverted the draconic smelt to dust recipe as we added a pulverise to dust recipe in the last update

**Comment by TheBedrockMaster** [comment]
Is this file being used for JEI blacklisting now? If so I can do a big cleanup.

**Pull request merged**
